name: API Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17' # Укажите нужную версию JDK

    - name: Build project
      run: ./gradlew build # или другой инструмент сборки, например, mvn clean install

    - name: Run tests
      run: ./gradlew test # команда для запуска тестов